name: New workflow
on: [push]
jobs:
  build:
    name: Run tests
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@actions

      - name: swift test --generate-linuxmain
        uses: swift test --generate-linuxmain

      - name: swift test
        uses: swift test