disabled_rules: # rule identifiers to exclude from running
  - trailing_whitespace
opt_in_rules: # some rules are only opt-in
  - control_statement
  - empty_count
  - trailing_newline
  - colon
  - comma
included: # paths to include during linting. `--path` is ignored if present.
  - Sources
  # - ProjectTests
  # - ProjectUITests
excluded: # paths to ignore during linting. Takes precedence over `included`.
  # - Example
  # - SANetworkService
  # - Tests
  # - .build
  # - .git
  # - .swiftpm
  # - Public

# # configurable rules can be customized from this configuration file
# # binary rules can set their severity level
force_cast: warning # implicitly. Give warning only for force casting

force_try:
  severity: warning # explicitly. Give warning only for force try

identifier_name:
  min_length: 1
  max_length: 50

line_length:
  - 400
  - 500

type_body_length:
  - 300 # warning
  - 400 # error
   
# # naming rules can set warnings/errors for min_length and max_length
# # additionally they can set excluded names
type_name:
  min_length: 4 # only warning
  max_length: # warning and error
    warning: 50
    error: 65
  excluded: iPhone # excluded via string
reporter: "xcode"